### ISSUE TITLE
new link to subscribe for live sessions ?

### ISSUE THREAD

**Issue by SunChero** [Azure/FTALive-Sessions#217]
i used to use https://fasttrack.azure.com/live to see all upcoming sessions and subscribe to them 
now the link is no longer working 
is there a new one ?

thank you

**Comment by kaslough** [comment]
I believe http://aka.ms/ftalive is the link you crave.

From: Adil Ha ***@***.***>
Sent: Tuesday, May 30, 2023 10:47 AM
To: Azure/FTALive-Sessions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure/FTALive-Sessions] new link to subscribe for live sessions ? (Issue #217)


i used to use https://fasttrack.azure.com/live to see all upcoming sessions and subscribe to them
now the link is no longer working
is there a new one ?

thank you

-

**Comment by SunChero** [comment]
thank you that similar to what i was looking for 
except the import meeting to outlook is not working !! 

but thank you that basically answer my question
have a great day
